baseURL = 'https://note.killliu.com/'
title = "killliu's note"
languageCode = "en"
theme = "color-your-world"

# Used only in the RSS file
copyright = "Copyright © 2022 killliu 粤ICP备14085800号-1"

enableEmoji = true
enableInlineShortcodes = true

paginate = 3

# TEST
# Netlify _headers
[outputs]
  home    = [ "HTML", "RSS", "HEADERS" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."text/netlify"]
  suffixes  = [ "" ]
  delimiter = ""

[outputFormats.HEADERS]
  mediaType       = "text/netlify"
  baseName        = "_headers"
  isPlainText     = true
  notAlternative  = true

[markup.highlight]
  # To make use of the custom Chroma, this should be false
  # The default is true
  noClasses = false

[params]
  
  description = "killliu's personal website"
  
  author      = "killliu"
  authorDesc  = "Some indescribable horror."
  
  footerText = [ "Copyright © 2022 killliu 粤ICP备14085800号-1" ]
  
  # Site cover, for Open Graph, Twitter Cards and Schema.org
  # It will be used if the current page doesn't have a image cover
  # File will be picked from the "assets" directory
  # Comment the lines if you don't want to use it
  #cover     = "img/cover.jpg"
  #coverAlt  = "A placeholder that doesn't deserve to be described."
  
  # Shows a message in the footer about JavaScript being disabled
  # The default is false
  hasNoscriptNotice = true
  
  # Default path for images in posts
  # ie.: "content/some-post/img"
  # Can also be set PER PAGE
  # It can be used to reduce repetition
  # There's no default value
  imgPath = "img"
  
  # Default classes for markup image 
  # Modifies the default behavior of images placed via markdown
  # Can also be set PER PAGE via front matter
  # Available classes are: border and borderless
  # There's no default value
  markupImgClass = ""
  
  # This will append a separator (of your choice) along the site title to your <title>
  # ie.: | ❚ - – — • ⚫ 
  # You can disabled it PER PAGE by using "disableTitleSeparator" at front
  # matter or disable it entirely by commenting the line below
  titleSeparator = "|"
  
  [params.search]
  
    # Enable search form (at the post list)
    # The default value is false
    enable = true
  
    # Limit search results
    # The default value is 30
    maxResults = 15
    
    # Limit seach field input and pattern matching
    minLength = 2   # Default is 3
    maxLength = 42  # Default is 32
    
    # Optional placeholder for search field
    placeholder = "ie.: lorem ipsum"
    

  [params.style]
    isDark = true

    # Disable the use of system settings (prefers-color-scheme)
    # The default is false
    ignoreSystemSettings = false

    # Accent colors for dark and light mode respectively
    darkAccent   = "#1dbc91" # Default is "#1dbc91"
    lightAccent  = "#1f676b" # Default is "#1f676b"

    presets = [ "#225670", "#dd587c", "#902b37", "#f3a530", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd" ]

    # Use an icon or text for footnote return links
    # The default is false
    hasIconAsFootnoteReturnLink = true
    
    # For the social shortcode
    # Use flexbox (with flex-grow) or grid (equal width)
    # The default is false
    socialIsFlex = false
    
    # Keep anchor links hidden until it's focused/hovered
    # The default is false
    hideAnchors = true
    
    # To make use of the custom Chroma, this should be true
    # and "noClasses" (at markup.highlight) should be false
    # The default is true
    useCustomChroma = true

    # CSS animation transition when changing colors
    # The default is ".5s ease"
    changeTransition = ".3s ease"
    
  [params.notFound]
    title         = "Page not found"
    description   = "This page was not found."
    paragraph     = "Nothing to see here, buddy."
    
  [params.social.centralized]
    #facebook      = [ "killliu" ]
    #flickr        = [ "<username>" ]
    github        = [ "killliu" ]
    #gitlab        = [ "<username>" ]
    #3instagram     = [ "<username>" ]
    #keybase       = [ "<username>" ]
    #linkedin      = [ "<username>" ]
    #medium        = [ "<username>" ]
    #reddit        = [ "<username>" ]
    #snapchat      = [ "<username>" ]
    #soundcloud    = [ "<username>" ]
    #stackOverflow = [ "<username>" ]
    #strava        = [ "<username>" ]
    #telegram      = [ "<username>" ]
    #twitch        = [ "<username>" ]
    twitter       = [ "@killliu" ]
    #vimeo         = [ "<username>" ]
    #whatsapp      = [ "<number>" ]
    #xing          = [ "<username>" ]
    #youtube       = [ "<channelid>" ]
    #entry         = [ "username", "label (optional)" ]
    
    # The "entry" here IS important. It's used to load the data.

  [params.social.decentralized]
  
    [params.social.decentralized.element]
      1 = [ "http://killliu.com/", "killliu" ]
    
    
[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[languages]

  [languages.en]
  
    languageName = "English"

    [languages.en.menu]

      [[languages.en.menu.main]]
        name = "Posts"
        weight = 2
        url = "posts/"
      
      [[languages.en.menu.main]]
        name = "About Me"
        weight = 3
        url = "contact/"
          